let a = true;
let b = 1;
let c = "text";
console.log(a + b, a + c, b + c);
console.log(a * b, a * c, b * c);
console.log(a / b, a / c, b / c);
console.log(Number(a));
console.log(String(a));
console.log(Boolean(b));
console.log(String(b));
console.log(Boolean(c));
